
#
#  Determine your Fortran compiler and some of its flags:

F95 = gfortran 

F95FLAGS = -O3 -I./
F95LINKFLAGS = -O3 -I./


.SUFFIXES:

%.o : %.mod

%.o: %.f95
	$(F95) $(F95FLAGS) -o $@ -c $<

%: %.o
	$(F95) $(F95LINKFLAGS) -o $@ $^

%.exe: %.o
	$(F95) $(F95LINKFLAGS) $(OBJS) -o $@ $^

#
# Seeking for and picking up files from directories:
#
vpath %.f95 FMinterval/ FMquad/ FMrational/ FMsamples/

OBJS = fmsave.o fm.o  fmzm90.o \
      fm_interval.o  \
      fm_doubleint.o fm_quadint.o fm_quadreal.o \
      fm_rational.o  

executables = SampleFM.exe TestFM.exe \
               fminFMv2.exe \
               IntervalExamplesFM.exe SampleFMinterval.exe TestFMinterval.exe \
               SampleDQ.exe TestFMdoubleInt.exe TestFMquadInt.exe TestFMquadReal.exe \
               SampleFMrational.exe TestFMrational.exe 

all: $(OBJS) $(executables)

.PHONY: clean run 

clean: 
	# remove all files generated by the compiler and by the .exe files
	rm -f *.o *.mod *.out *.OUT *.INP *.ARGS *.VARS *.MODS *.PASS1 *.PASS2 *.VARS2 \
	INTERVAL_EXAMPLES* TEMPFM RWtest 
	# remove all executable files
	rm -f $(executables)

run: $(executables)
	for f in $(executables); do \
	echo "**************************************************"; \
	echo; echo "RUNNING $$f ..." ; \
	./$$f ; \
	echo "**************************************************"; \
	done 

